import { describe, expect, it } from 'vitest';
import { keccak256 } from 'viem';
import {
  ACTION_TEMPLATES,
  generateActionsFromTemplate,
  parseActionsToTemplates,
} from '../../../actionTemplates';
import { assertNoMatch, assertRoundTrip } from '../../__tests__/roundTrip';
import { OP_RECOVERY_ADDRESSES, SEND_MESSAGE_SIGNATURE } from '../shared';
import { opTokenBuyerRecoveryStageOne } from '../stage-one';
import { opTokenBuyerRecoveryStageTwo } from '../stage-two';

const VERIFIED_BALANCE_ETH = '1.090910787345462498';

// Independently generated by proposals/2026-09-op-tokenbuyer-recovery/encode.sh
// using Foundry cast. Hashing keeps the fixtures readable while pinning every
// byte of the outer and nested calldata.
const CAST_CALLDATA_HASHES = {
  stageOne: [
    '0x091dbdff3e12825fe89b1a474f626eb5d62b3d5697a9214f97d7af424e5138b3',
    '0xb316f2af1b826a59e9600676c6b907d16f0552fd3ec4a435343ff10094a5be56',
    '0x5480574e51fdfd03a2de6ce3ccb0edeba2723559b7cadd1b1a2876ae6bf55ae6',
  ],
  stageTwo: [
    '0xe1c9d407f560a8b927baa7d806414c6cbed3042ef1d7d7772cda95fbbaf58e75',
    '0xb9163e407aa677df5a2bd785612b35509d89677ee8575c2fb3777d4b72773e40',
  ],
} as const;

describe('OP TokenBuyer recovery builders', () => {
  it('encodes Stage 1 as the exact three Timelock v1 messenger calls', () => {
    const actions = opTokenBuyerRecoveryStageOne.encode({}, {});

    expect(opTokenBuyerRecoveryStageOne.requiredProposalType).toBe('timelock_v1');
    expect(actions).toHaveLength(3);
    expect(actions.map((action) => action.target)).toEqual([
      OP_RECOVERY_ADDRESSES.l1Messenger,
      OP_RECOVERY_ADDRESSES.l1Messenger,
      OP_RECOVERY_ADDRESSES.l1Messenger,
    ]);
    expect(actions.every((action) => action.signature === SEND_MESSAGE_SIGNATURE)).toBe(true);
    expect(actions.map((action) => keccak256(action.calldata as `0x${string}`))).toEqual(
      CAST_CALLDATA_HASHES.stageOne,
    );
    assertRoundTrip(opTokenBuyerRecoveryStageOne, {});

    const fromPicker = generateActionsFromTemplate(
      'admin-op-tokenbuyer-recovery-stage-1',
      {},
    );
    expect(fromPicker).toEqual(actions);
    expect(parseActionsToTemplates(actions)).toMatchObject([
      { templateId: 'admin-op-tokenbuyer-recovery-stage-1', fieldValues: {} },
    ]);
  });

  it('encodes Stage 2 as the exact two standard proposal messenger calls', () => {
    const fields = { proxyBalanceEth: VERIFIED_BALANCE_ETH };
    const actions = opTokenBuyerRecoveryStageTwo.encode(fields, {});

    expect(opTokenBuyerRecoveryStageTwo.requiredProposalType).toBe('standard');
    expect(actions).toHaveLength(2);
    expect(actions.every((action) => action.target === OP_RECOVERY_ADDRESSES.l1Messenger)).toBe(true);
    expect(actions.every((action) => action.signature === SEND_MESSAGE_SIGNATURE)).toBe(true);
    expect(actions.map((action) => keccak256(action.calldata as `0x${string}`))).toEqual(
      CAST_CALLDATA_HASHES.stageTwo,
    );
    assertRoundTrip(opTokenBuyerRecoveryStageTwo, fields);

    expect(ACTION_TEMPLATES['admin-op-tokenbuyer-recovery-stage-2'].fields)
      .toMatchObject([{ name: 'proxyBalanceEth', required: true }]);
    expect(parseActionsToTemplates(actions)).toMatchObject([
      {
        templateId: 'admin-op-tokenbuyer-recovery-stage-2',
        fieldValues: fields,
      },
    ]);
  });

  it('refuses to encode a Stage 2 bridge with zero ETH', () => {
    expect(() =>
      opTokenBuyerRecoveryStageTwo.encode(
        { proxyBalanceEth: '0' },
        {},
      ),
    ).toThrow('must be greater than zero');
  });

  it('does not decode the stages in the wrong order', () => {
    const stageOne = opTokenBuyerRecoveryStageOne.encode({}, {});
    const reordered = [stageOne[1], stageOne[0], stageOne[2]];
    assertNoMatch(opTokenBuyerRecoveryStageOne, reordered);
  });
});
