/**
 * Activity definitions for the 5 mutually-exclusive proposal outcomes:
 * succeeded, defeated, cancelled, queued, executed.
 *
 * All five share the `proposals` producerKey (no buildQuery — that lives on
 * proposalCreated). Their `processRows` is generated by `makeOutcomeProcessor`
 * which guarantees mutual exclusivity via `classifyOutcome`. A single row
 * yields at most one outcome item.
 *
 * Co-located in one file because they're trivial wrappers around the shared
 * factory — splitting into five files would be pure noise.
 *
 * Source: extracted from `useActivityFeed.ts:269-357` (the outcome-emission
 * half of processProposals).
 */

import type { ActivityDefinition } from '../types';
import { ApiProposalRow, makeOutcomeProcessor } from './_proposalProducer';

export const proposalSucceededDefinition: ActivityDefinition<ApiProposalRow> = {
  type: 'proposal_succeeded',
  producerKey: 'proposals',
  processRows: makeOutcomeProcessor('succeeded'),
};

export const proposalDefeatedDefinition: ActivityDefinition<ApiProposalRow> = {
  type: 'proposal_defeated',
  producerKey: 'proposals',
  processRows: makeOutcomeProcessor('defeated'),
};

export const proposalCancelledDefinition: ActivityDefinition<ApiProposalRow> = {
  type: 'proposal_cancelled',
  producerKey: 'proposals',
  processRows: makeOutcomeProcessor('cancelled'),
};

export const proposalQueuedDefinition: ActivityDefinition<ApiProposalRow> = {
  type: 'proposal_queued',
  producerKey: 'proposals',
  processRows: makeOutcomeProcessor('queued'),
};

export const proposalExecutedDefinition: ActivityDefinition<ApiProposalRow> = {
  type: 'proposal_executed',
  producerKey: 'proposals',
  processRows: makeOutcomeProcessor('executed'),
};
